$kind: http-request
name: One Book with invalid Id
method: GET
url: '{{baseURL}}/api/books/150'
order: 10000
scripts:
  - type: afterResponse
    language: text/javascript
    code: |-
      pm.test("Status code is 404", function () { pm.response.to.have.status(404); });
