$kind: http-request
name: Post data with invalid object
description: >-
  This is a POST request, submitting data to an API via the request body. This
  request submits JSON data, and the data is reflected in the response.


  A successful POST request typically returns a `200 OK` or `201 Created`
  response code.
url: "{{baseURL}}/api/books"
method: POST
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: '{"Title":"{{$randomWord}}", "Price": {{$randomPrice}}}'
scripts:
  - type: afterResponse
    code: pm.test("Successful POST request", function () {
      pm.expect(pm.response.code).to.be.oneOf([200, 201]); });
    language: text/javascript
order: 2315
