$kind: http-request
name: Update Book
method: PUT
url: '{{baseURL}}/api/books/{{bookId}}'
order: 8000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    { "id": {{bookId}}, "title": "The Catcdfdsf", "price": 489 }
