$kind: http-request
name: Update Book
method: PUT
url: "{{baseURL}}/api/v2/books/1"
order: 9000
headers:
  Content-Type: application/json
body:
  type: json
  content: "{\r\n\r\n    \    \"title\": \"The Catcdfdsf\",\r\n\r\n    \    \"price\": 489,\r\n\r\n    \    \"author\": \"Zülal\"\r\n\r\n    }"
