$kind: http-request
name: One Book with Invalid Object
url: "{{baseURL}}/api/v1/books"
method: POST
body:
  type: json
  content: '{"Title":"a", "Price": 1}'
scripts:
  - type: afterResponse
    code: pm.test("Status code is 400", function () {
      pm.response.to.have.status(400); });
    language: text/javascript
order: 13000
