$kind: http-request
name: Login
url: "{{baseURL}}/api/auth/login"
method: POST
body:
  type: json
  content: "{\r

    \    \"email\": \"test@example.com\",\r

    \    \"password\": \"Test1234\"\r

    }"
order: 970063499997170
