$kind: http-request
name: Register
url: "{{baseURL}}/api/auth/register"
method: POST
body:
  type: json
  content: "{\r

    \    \"email\": \"zulal@example.com\",\r

    \    \"password\": \"Test1234\",\r

    \    \"firstName\": \"Zulal\",\r

    \    \"lastName\": \"User\"\r

    }"
order: 1783329152777
