# Use this workspace to collaborate
workspace:
  id: bd37104c-64cf-48e6-b887-19b346fccf81

localResources:
  specs:
    - ../postman/specs/New Specification/New Specification.yaml
    - ../postman/specs/New Specification-1/New Specification-1.smithy
